/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize, de::Error as _};

use super::{super::LabrinthClient, super::models, ContentType, Error, ResponseContent};

/// struct for typed errors of method [`forge_updates`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ForgeUpdatesError {
    Status400(models::InvalidInputError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsError {
    UnknownValue(serde_json::Value),
}

impl LabrinthClient {
    /// If you're a Forge mod developer, your Modrinth mods have an automatically generated `updates.json` using the [Forge Update Checker](https://docs.minecraftforge.net/en/latest/misc/updatechecker/).  The only setup is to insert the URL into the `[[mods]]` section of your `mods.toml` file as such:  ```toml [[mods]] # the other stuff here - ID, version, display name, etc. updateJSONURL = \"https://api.modrinth.com/updates/{slug|ID}/forge_updates.json\" ```  Replace `{slug|id}` with the slug or ID of your project.  Modrinth will handle the rest! When you update your mod, Forge will notify your users that their copy of your mod is out of date.  Make sure that the version format you use for your Modrinth releases is the same as the version format you use in your `mods.toml`. If you use a format such as `1.2.3-forge` or `1.2.3+1.19` with your Modrinth releases but your `mods.toml` only has `1.2.3`, the update checker may not function properly.  If you're using NeoForge, NeoForge versions will, by default, not appear in the default URL. You will need to add `?neoforge=only` to show your NeoForge-only versions, or `?neoforge=include` for both.  ```toml [[mods]] # the other stuff here - ID, version, display name, etc. updateJSONURL = \"https://api.modrinth.com/updates/{slug|ID}/forge_updates.json?neoforge=only\" ```
    pub async fn forge_updates(
        &self,
        id_pipe_slug: &str,
        neoforge: Option<&str>,
    ) -> Result<models::ForgeUpdates, Error<ForgeUpdatesError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;
        let p_query_neoforge = neoforge;

        let mut uri_path = "/updates/{id|slug}/forge_updates.json".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref param_value) = p_query_neoforge {
            req_builder = req_builder.query(&[("neoforge", &param_value.to_string())])?;
        }

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ForgeUpdates`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::ForgeUpdates`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<ForgeUpdatesError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn statistics(&self) -> Result<models::Statistics, Error<StatisticsError>> {
        let uri_path = "/statistics".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Statistics`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Statistics`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<StatisticsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }
}
