/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize, de::Error as _};

use super::{super::LabrinthClient, super::models, ContentType, Error, ResponseContent};

/// struct for typed errors of method [`delete_notification`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteNotificationError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_notifications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteNotificationsError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_notification`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetNotificationError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_notifications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetNotificationsError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_user_notifications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserNotificationsError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`read_notification`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReadNotificationError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`read_notifications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReadNotificationsError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

impl LabrinthClient {
    pub async fn delete_notification(
        &self,
        id: &str,
    ) -> Result<(), Error<DeleteNotificationError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;

        let mut uri_path = "/notification/{id}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteNotificationError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn delete_notifications(
        &self,
        ids: &str,
    ) -> Result<(), Error<DeleteNotificationsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;

        let uri_path = "/notifications".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteNotificationsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_notification(
        &self,
        id: &str,
    ) -> Result<models::Notification, Error<GetNotificationError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;

        let mut uri_path = "/notification/{id}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Notification`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Notification`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetNotificationError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_notifications(
        &self,
        ids: &str,
    ) -> Result<Vec<models::Notification>, Error<GetNotificationsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;

        let uri_path = "/notifications".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Notification&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Notification&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetNotificationsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_user_notifications(
        &self,
        id_pipe_username: &str,
    ) -> Result<Vec<models::Notification>, Error<GetUserNotificationsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;

        let mut uri_path = "/user/{id|username}/notifications".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Notification&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Notification&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetUserNotificationsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn read_notification(&self, id: &str) -> Result<(), Error<ReadNotificationError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;

        let mut uri_path = "/notification/{id}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ReadNotificationError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn read_notifications(&self, ids: &str) -> Result<(), Error<ReadNotificationsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;

        let uri_path = "/notifications".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ReadNotificationsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }
}
