/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize, de::Error as _};

use super::{super::LabrinthClient, super::models, ContentType, Error, ResponseContent};

/// struct for typed errors of method [`add_gallery_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddGalleryImageError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`change_project_icon`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChangeProjectIconError {
    Status400(models::InvalidInputError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`check_project_validity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CheckProjectValidityError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_project`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateProjectError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_gallery_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteGalleryImageError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_project`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteProjectError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_project_icon`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteProjectIconError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`follow_project`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FollowProjectError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_dependencies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDependenciesError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_project`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetProjectError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetProjectsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`modify_gallery_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModifyGalleryImageError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`modify_project`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModifyProjectError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchProjectsError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`random_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RandomProjectsError {
    Status400(models::InvalidInputError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`schedule_project`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScheduleProjectError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchProjectsError {
    Status400(models::InvalidInputError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unfollow_project`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnfollowProjectError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

impl LabrinthClient {
    /// Modrinth allows you to upload files of up to 5MiB to a project's gallery.
    pub async fn add_gallery_image(
        &self,
        id_pipe_slug: &str,
        ext: &str,
        featured: bool,
        title: Option<&str>,
        description: Option<&str>,
        ordering: Option<i32>,
        body: Option<std::path::PathBuf>,
    ) -> Result<(), Error<AddGalleryImageError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;
        let p_query_ext = ext;
        let p_query_featured = featured;
        let p_query_title = title;
        let p_query_description = description;
        let p_query_ordering = ordering;
        let p_body_body = body;

        let mut uri_path = "/project/{id|slug}/gallery".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        req_builder = req_builder.query(&[("ext", &p_query_ext.to_string())])?;
        req_builder = req_builder.query(&[("featured", &p_query_featured.to_string())])?;
        if let Some(ref param_value) = p_query_title {
            req_builder = req_builder.query(&[("title", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_description {
            req_builder = req_builder.query(&[("description", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_ordering {
            req_builder = req_builder.query(&[("ordering", &param_value.to_string())])?;
        }
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        if let Some(param_value) = p_body_body {
            let file = compio::fs::File::open(param_value).await?;
            req_builder = req_builder.body(file);
        }

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<AddGalleryImageError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    /// The new icon may be up to 256KiB in size.
    pub async fn change_project_icon(
        &self,
        id_pipe_slug: &str,
        ext: &str,
        body: Option<std::path::PathBuf>,
    ) -> Result<(), Error<ChangeProjectIconError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;
        let p_query_ext = ext;
        let p_body_body = body;

        let mut uri_path = "/project/{id|slug}/icon".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        req_builder = req_builder.query(&[("ext", &p_query_ext.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        if let Some(param_value) = p_body_body {
            let file = compio::fs::File::open(param_value).await?;
            req_builder = req_builder.body(file);
        }

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ChangeProjectIconError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn check_project_validity(
        &self,
        id_pipe_slug: &str,
    ) -> Result<models::ProjectIdentifier, Error<CheckProjectValidityError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;

        let mut uri_path = "/project/{id|slug}/check".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ProjectIdentifier`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::ProjectIdentifier`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<CheckProjectValidityError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn create_project(
        &self,
        data: models::CreatableProject,
        icon: Option<std::path::PathBuf>,
    ) -> Result<models::Project, Error<CreateProjectError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_form_data = data;
        let p_form_icon = icon;

        let uri_path = "/project".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        let mut multipart_form = cyper::multipart::Form::new();
        multipart_form = multipart_form.text("data", serde_json::to_string(&p_form_data)?);
        if let Some(ref param_value) = p_form_icon {
            multipart_form = multipart_form.file("icon", param_value).await?;
        }
        req_builder = req_builder.multipart(multipart_form)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Project`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Project`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<CreateProjectError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn delete_gallery_image(
        &self,
        id_pipe_slug: &str,
        url: &str,
    ) -> Result<(), Error<DeleteGalleryImageError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;
        let p_query_url = url;

        let mut uri_path = "/project/{id|slug}/gallery".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        req_builder = req_builder.query(&[("url", &p_query_url.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteGalleryImageError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn delete_project(
        &self,
        id_pipe_slug: &str,
    ) -> Result<(), Error<DeleteProjectError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;

        let mut uri_path = "/project/{id|slug}".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteProjectError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn delete_project_icon(
        &self,
        id_pipe_slug: &str,
    ) -> Result<(), Error<DeleteProjectIconError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;

        let mut uri_path = "/project/{id|slug}/icon".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteProjectIconError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn follow_project(
        &self,
        id_pipe_slug: &str,
    ) -> Result<(), Error<FollowProjectError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;

        let mut uri_path = "/project/{id|slug}/follow".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<FollowProjectError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_dependencies(
        &self,
        id_pipe_slug: &str,
    ) -> Result<models::ProjectDependencyList, Error<GetDependenciesError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;

        let mut uri_path = "/project/{id|slug}/dependencies".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ProjectDependencyList`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::ProjectDependencyList`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetDependenciesError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_project(
        &self,
        id_pipe_slug: &str,
    ) -> Result<models::Project, Error<GetProjectError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;

        let mut uri_path = "/project/{id|slug}".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Project`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Project`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetProjectError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_projects(
        &self,
        ids: &str,
    ) -> Result<Vec<models::Project>, Error<GetProjectsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;

        let uri_path = "/projects".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Project&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Project&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetProjectsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn modify_gallery_image(
        &self,
        id_pipe_slug: &str,
        url: &str,
        featured: Option<bool>,
        title: Option<&str>,
        description: Option<&str>,
        ordering: Option<i32>,
    ) -> Result<(), Error<ModifyGalleryImageError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;
        let p_query_url = url;
        let p_query_featured = featured;
        let p_query_title = title;
        let p_query_description = description;
        let p_query_ordering = ordering;

        let mut uri_path = "/project/{id|slug}/gallery".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        req_builder = req_builder.query(&[("url", &p_query_url.to_string())])?;
        if let Some(ref param_value) = p_query_featured {
            req_builder = req_builder.query(&[("featured", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_title {
            req_builder = req_builder.query(&[("title", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_description {
            req_builder = req_builder.query(&[("description", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_ordering {
            req_builder = req_builder.query(&[("ordering", &param_value.to_string())])?;
        }
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ModifyGalleryImageError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn modify_project(
        &self,
        id_pipe_slug: &str,
        editable_project: Option<models::EditableProject>,
    ) -> Result<(), Error<ModifyProjectError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;
        let p_body_editable_project = editable_project;

        let mut uri_path = "/project/{id|slug}".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_editable_project)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ModifyProjectError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn patch_projects(
        &self,
        ids: &str,
        patch_projects_body: Option<models::PatchProjectsBody>,
    ) -> Result<(), Error<PatchProjectsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;
        let p_body_patch_projects_body = patch_projects_body;

        let uri_path = "/projects".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_patch_projects_body)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<PatchProjectsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn random_projects(
        &self,
        count: i32,
    ) -> Result<Vec<models::Project>, Error<RandomProjectsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_count = count;

        let uri_path = "/projects_random".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        req_builder = req_builder.query(&[("count", &p_query_count.to_string())])?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Project&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Project&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<RandomProjectsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn schedule_project(
        &self,
        id_pipe_slug: &str,
        schedule: Option<models::Schedule>,
    ) -> Result<(), Error<ScheduleProjectError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;
        let p_body_schedule = schedule;

        let mut uri_path = "/project/{id|slug}/schedule".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_schedule)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ScheduleProjectError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn search_projects(
        &self,
        query: Option<&str>,
        facets: Option<&str>,
        index: Option<&str>,
        offset: Option<i32>,
        limit: Option<i32>,
    ) -> Result<models::SearchResults, Error<SearchProjectsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_query = query;
        let p_query_facets = facets;
        let p_query_index = index;
        let p_query_offset = offset;
        let p_query_limit = limit;

        let uri_path = "/search".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref param_value) = p_query_query {
            req_builder = req_builder.query(&[("query", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_facets {
            req_builder = req_builder.query(&[("facets", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_index {
            req_builder = req_builder.query(&[("index", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_offset {
            req_builder = req_builder.query(&[("offset", &param_value.to_string())])?;
        }
        if let Some(ref param_value) = p_query_limit {
            req_builder = req_builder.query(&[("limit", &param_value.to_string())])?;
        }

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::SearchResults`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::SearchResults`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<SearchProjectsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn unfollow_project(
        &self,
        id_pipe_slug: &str,
    ) -> Result<(), Error<UnfollowProjectError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;

        let mut uri_path = "/project/{id|slug}/follow".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<UnfollowProjectError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }
}
