/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize, de::Error as _};

use super::{super::LabrinthClient, super::models, ContentType, Error, ResponseContent};

/// struct for typed errors of method [`add_team_member`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddTeamMemberError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_team_member`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTeamMemberError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_project_team_members`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetProjectTeamMembersError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_team_members`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTeamMembersError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_teams`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTeamsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`join_team`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JoinTeamError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`modify_team_member`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModifyTeamMemberError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`transfer_team_ownership`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransferTeamOwnershipError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

impl LabrinthClient {
    pub async fn add_team_member(
        &self,
        id: &str,
        user_identifier: Option<models::UserIdentifier>,
    ) -> Result<(), Error<AddTeamMemberError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;
        let p_body_user_identifier = user_identifier;

        let mut uri_path = "/team/{id}/members".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_user_identifier)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<AddTeamMemberError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn delete_team_member(
        &self,
        id: &str,
        id_pipe_username: &str,
    ) -> Result<(), Error<DeleteTeamMemberError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;
        let p_path_id_pipe_username = id_pipe_username;

        let mut uri_path = "/team/{id}/members/{id|username}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteTeamMemberError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_project_team_members(
        &self,
        id_pipe_slug: &str,
    ) -> Result<Vec<models::TeamMember>, Error<GetProjectTeamMembersError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_slug = id_pipe_slug;

        let mut uri_path = "/project/{id|slug}/members".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|slug", "}"),
            &super::urlencode(p_path_id_pipe_slug),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::TeamMember&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::TeamMember&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetProjectTeamMembersError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_team_members(
        &self,
        id: &str,
    ) -> Result<Vec<models::TeamMember>, Error<GetTeamMembersError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;

        let mut uri_path = "/team/{id}/members".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::TeamMember&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::TeamMember&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetTeamMembersError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_teams(
        &self,
        ids: &str,
    ) -> Result<Vec<Vec<models::TeamMember>>, Error<GetTeamsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;

        let uri_path = "/teams".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;Vec&lt;models::TeamMember&gt;&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;Vec&lt;models::TeamMember&gt;&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetTeamsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn join_team(&self, id: &str) -> Result<(), Error<JoinTeamError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;

        let mut uri_path = "/team/{id}/join".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<JoinTeamError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn modify_team_member(
        &self,
        id: &str,
        id_pipe_username: &str,
        modify_team_member_body: Option<models::ModifyTeamMemberBody>,
    ) -> Result<(), Error<ModifyTeamMemberError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;
        let p_path_id_pipe_username = id_pipe_username;
        let p_body_modify_team_member_body = modify_team_member_body;

        let mut uri_path = "/team/{id}/members/{id|username}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_modify_team_member_body)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ModifyTeamMemberError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn transfer_team_ownership(
        &self,
        id: &str,
        user_identifier: Option<models::UserIdentifier>,
    ) -> Result<(), Error<TransferTeamOwnershipError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;
        let p_body_user_identifier = user_identifier;

        let mut uri_path = "/team/{id}/owner".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_user_identifier)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<TransferTeamOwnershipError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }
}
