/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize, de::Error as _};

use super::{super::LabrinthClient, super::models, ContentType, Error, ResponseContent};

/// struct for typed errors of method [`delete_thread_message`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteThreadMessageError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_open_reports`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetOpenReportsError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_report`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetReportError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_reports`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetReportsError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_thread`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetThreadError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_threads`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetThreadsError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`modify_report`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModifyReportError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`send_thread_message`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendThreadMessageError {
    Status400(models::InvalidInputError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`submit_report`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubmitReportError {
    Status400(models::InvalidInputError),
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

impl LabrinthClient {
    pub async fn delete_thread_message(
        &self,
        id: &str,
    ) -> Result<(), Error<DeleteThreadMessageError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;

        let mut uri_path = "/message/{id}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteThreadMessageError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_open_reports(
        &self,
        count: Option<i32>,
    ) -> Result<Vec<models::Report>, Error<GetOpenReportsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_count = count;

        let uri_path = "/report".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref param_value) = p_query_count {
            req_builder = req_builder.query(&[("count", &param_value.to_string())])?;
        }
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Report&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Report&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetOpenReportsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_report(&self, id: &str) -> Result<models::Report, Error<GetReportError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;

        let mut uri_path = "/report/{id}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Report`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Report`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetReportError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_reports(
        &self,
        ids: &str,
    ) -> Result<Vec<models::Report>, Error<GetReportsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;

        let uri_path = "/reports".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Report&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Report&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetReportsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_thread(&self, id: &str) -> Result<models::Thread, Error<GetThreadError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;

        let mut uri_path = "/thread/{id}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Thread`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Thread`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetThreadError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_threads(
        &self,
        ids: &str,
    ) -> Result<Vec<models::Thread>, Error<GetThreadsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;

        let uri_path = "/threads".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Thread&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Thread&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetThreadsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn modify_report(
        &self,
        id: &str,
        modify_report_request: Option<models::ModifyReportRequest>,
    ) -> Result<(), Error<ModifyReportError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;
        let p_body_modify_report_request = modify_report_request;

        let mut uri_path = "/report/{id}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_modify_report_request)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ModifyReportError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn send_thread_message(
        &self,
        id: &str,
        thread_message_body: Option<models::ThreadMessageBody>,
    ) -> Result<models::Thread, Error<SendThreadMessageError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id = id;
        let p_body_thread_message_body = thread_message_body;

        let mut uri_path = "/thread/{id}".to_owned();
        uri_path = uri_path.replace(concat!("{", "id", "}"), &super::urlencode(p_path_id));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_thread_message_body)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Thread`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Thread`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<SendThreadMessageError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    /// Bring a project, user, or version to the attention of the moderators by reporting it.
    pub async fn submit_report(
        &self,
        creatable_report: Option<models::CreatableReport>,
    ) -> Result<models::Report, Error<SubmitReportError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_body_creatable_report = creatable_report;

        let uri_path = "/report".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_creatable_report)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Report`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Report`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<SubmitReportError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }
}
