/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize, de::Error as _};

use super::{super::LabrinthClient, super::models, ContentType, Error, ResponseContent};

/// struct for typed errors of method [`change_user_icon`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChangeUserIconError {
    Status400(models::InvalidInputError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_user_icon`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteUserIconError {
    Status400(models::InvalidInputError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_followed_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFollowedProjectsError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_payout_history`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPayoutHistoryError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_user_from_auth`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserFromAuthError {
    Status401(models::AuthError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_user_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserProjectsError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUsersError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`modify_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModifyUserError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`withdraw_payout`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WithdrawPayoutError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

impl LabrinthClient {
    /// The new avatar may be up to 2MiB in size.
    pub async fn change_user_icon(
        &self,
        id_pipe_username: &str,
        body: Option<std::path::PathBuf>,
    ) -> Result<(), Error<ChangeUserIconError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;
        let p_body_body = body;

        let mut uri_path = "/user/{id|username}/icon".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        if let Some(param_value) = p_body_body {
            let file = compio::fs::File::open(param_value).await?;
            req_builder = req_builder.body(file);
        }

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ChangeUserIconError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn delete_user_icon(
        &self,
        id_pipe_username: &str,
    ) -> Result<(), Error<DeleteUserIconError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;

        let mut uri_path = "/user/{id|username}/icon".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteUserIconError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_followed_projects(
        &self,
        id_pipe_username: &str,
    ) -> Result<Vec<models::Project>, Error<GetFollowedProjectsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;

        let mut uri_path = "/user/{id|username}/follows".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Project&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Project&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetFollowedProjectsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_payout_history(
        &self,
        id_pipe_username: &str,
    ) -> Result<models::UserPayoutHistory, Error<GetPayoutHistoryError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;

        let mut uri_path = "/user/{id|username}/payouts".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::UserPayoutHistory`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::UserPayoutHistory`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetPayoutHistoryError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_user(
        &self,
        id_pipe_username: &str,
    ) -> Result<models::User, Error<GetUserError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;

        let mut uri_path = "/user/{id|username}".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::User`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::User`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetUserError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_user_from_auth(&self) -> Result<models::User, Error<GetUserFromAuthError>> {
        let uri_path = "/user".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::User`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::User`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetUserFromAuthError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_user_projects(
        &self,
        id_pipe_username: &str,
    ) -> Result<Vec<models::Project>, Error<GetUserProjectsError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;

        let mut uri_path = "/user/{id|username}/projects".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Project&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Project&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetUserProjectsError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_users(&self, ids: &str) -> Result<Vec<models::User>, Error<GetUsersError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_query_ids = ids;

        let uri_path = "/users".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        req_builder = req_builder.query(&[("ids", &p_query_ids.to_string())])?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::User&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::User&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetUsersError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn modify_user(
        &self,
        id_pipe_username: &str,
        editable_user: Option<models::EditableUser>,
    ) -> Result<(), Error<ModifyUserError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;
        let p_body_editable_user = editable_user;

        let mut uri_path = "/user/{id|username}".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::PATCH, &uri_str)?;

        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };
        req_builder = req_builder.json(&p_body_editable_user)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<ModifyUserError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    /// Warning: certain amounts get withheld for fees. Please do not call this API endpoint without first acknowledging the warnings on the corresponding frontend page.
    pub async fn withdraw_payout(
        &self,
        id_pipe_username: &str,
        amount: i32,
    ) -> Result<(), Error<WithdrawPayoutError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_id_pipe_username = id_pipe_username;
        let p_query_amount = amount;

        let mut uri_path = "/user/{id|username}/payouts".to_owned();
        uri_path = uri_path.replace(
            concat!("{", "id|username", "}"),
            &super::urlencode(p_path_id_pipe_username),
        );
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        req_builder = req_builder.query(&[("amount", &p_query_amount.to_string())])?;
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<WithdrawPayoutError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }
}
