/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize, de::Error as _};

use super::{super::LabrinthClient, super::models, ContentType, Error, ResponseContent};

/// struct for typed errors of method [`delete_file_from_hash`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteFileFromHashError {
    Status401(models::AuthError),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_latest_version_from_hash`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLatestVersionFromHashError {
    Status400(),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_latest_versions_from_hashes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLatestVersionsFromHashesError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`version_from_hash`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VersionFromHashError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`versions_from_hashes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VersionsFromHashesError {
    Status400(),
    UnknownValue(serde_json::Value),
}

impl LabrinthClient {
    pub async fn delete_file_from_hash(
        &self,
        hash: &str,
        algorithm: &str,
        version_id: Option<&str>,
    ) -> Result<(), Error<DeleteFileFromHashError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_hash = hash;
        let p_query_algorithm = algorithm;
        let p_query_version_id = version_id;

        let mut uri_path = "/version_file/{hash}".to_owned();
        uri_path = uri_path.replace(concat!("{", "hash", "}"), &super::urlencode(p_path_hash));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::DELETE, &uri_str)?;

        req_builder = req_builder.query(&[("algorithm", &p_query_algorithm.to_string())])?;
        if let Some(ref param_value) = p_query_version_id {
            req_builder = req_builder.query(&[("version_id", &param_value.to_string())])?;
        }
        if let Some(ref apikey) = self.api_key {
            let key = apikey.key.clone();
            let value = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", value)?;
        };

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();

        if !status.is_client_error() && !status.is_server_error() {
            Ok(())
        } else {
            let content = resp.text().await?;
            let entity: Option<DeleteFileFromHashError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn get_latest_version_from_hash(
        &self,
        hash: &str,
        algorithm: &str,
        get_latest_version_from_hash_body: Option<models::GetLatestVersionFromHashBody>,
    ) -> Result<models::Version, Error<GetLatestVersionFromHashError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_hash = hash;
        let p_query_algorithm = algorithm;
        let p_body_get_latest_version_from_hash_body = get_latest_version_from_hash_body;

        let mut uri_path = "/version_file/{hash}/update".to_owned();
        uri_path = uri_path.replace(concat!("{", "hash", "}"), &super::urlencode(p_path_hash));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        req_builder = req_builder.query(&[("algorithm", &p_query_algorithm.to_string())])?;
        req_builder = req_builder.json(&p_body_get_latest_version_from_hash_body)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Version`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Version`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetLatestVersionFromHashError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    /// This is the same as [`/version_file/{hash}/update`](#operation/getLatestVersionFromHash) except it accepts multiple hashes.
    pub async fn get_latest_versions_from_hashes(
        &self,
        get_latest_versions_from_hashes_body: Option<models::GetLatestVersionsFromHashesBody>,
    ) -> Result<
        std::collections::HashMap<String, models::Version>,
        Error<GetLatestVersionsFromHashesError>,
    > {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_body_get_latest_versions_from_hashes_body = get_latest_versions_from_hashes_body;

        let uri_path = "/version_files/update".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        req_builder = req_builder.json(&p_body_get_latest_versions_from_hashes_body)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::Version&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::Version&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<GetLatestVersionsFromHashesError> =
                serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    pub async fn version_from_hash(
        &self,
        hash: &str,
        algorithm: &str,
        multiple: Option<bool>,
    ) -> Result<models::Version, Error<VersionFromHashError>> {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_path_hash = hash;
        let p_query_algorithm = algorithm;
        let p_query_multiple = multiple;

        let mut uri_path = "/version_file/{hash}".to_owned();
        uri_path = uri_path.replace(concat!("{", "hash", "}"), &super::urlencode(p_path_hash));
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::GET, &uri_str)?;

        req_builder = req_builder.query(&[("algorithm", &p_query_algorithm.to_string())])?;
        if let Some(ref param_value) = p_query_multiple {
            req_builder = req_builder.query(&[("multiple", &param_value.to_string())])?;
        }

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Version`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `models::Version`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<VersionFromHashError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }

    /// This is the same as [`/version_file/{hash}`](#operation/versionFromHash) except it accepts multiple hashes.
    pub async fn versions_from_hashes(
        &self,
        hash_list: Option<models::HashList>,
    ) -> Result<std::collections::HashMap<String, models::Version>, Error<VersionsFromHashesError>>
    {
        // add a prefix to parameters to efficiently prevent name collisions
        let p_body_hash_list = hash_list;

        let uri_path = "/version_files".to_owned();
        let uri_str = format!("{}{}", self.base_path, uri_path);
        #[allow(unused_mut)]
        let mut req_builder = self.http.request(http::Method::POST, &uri_str)?;

        req_builder = req_builder.json(&p_body_hash_list)?;

        let req = req_builder.build();
        let resp = self.http.execute(req).await?;

        let status = resp.status();
        let content_type = resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let content_type = super::ContentType::from(content_type);

        if !status.is_client_error() && !status.is_server_error() {
            let content = resp.text().await?;
            match content_type {
                ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::Version&gt;`",
                    )));
                }
                ContentType::Unsupported(unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::Version&gt;`"
                    ))));
                }
            }
        } else {
            let content = resp.text().await?;
            let entity: Option<VersionsFromHashesError> = serde_json::from_str(&content).ok();
            Err(Error::ResponseError(ResponseContent {
                status,
                content,
                entity,
            }))
        }
    }
}
