/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthError {
    /// The name of the error
    #[serde(rename = "error")]
    pub error: String,
    /// The contents of the error
    #[serde(rename = "description")]
    pub description: String,
}

impl AuthError {
    pub fn new(error: String, description: String) -> AuthError {
        AuthError { error, description }
    }
}
