/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseProject {
    /// The slug of a project, used for vanity URLs. Regex: ```^[\\w!@$()`.+,\"\\-']{3,64}$```
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The title or name of the project
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// A short description of the project
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A list of the categories that the project has
    #[serde(rename = "categories", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Vec<String>>,
    /// The client side support of the project
    #[serde(rename = "client_side", skip_serializing_if = "Option::is_none")]
    pub client_side: Option<ClientSide>,
    /// The server side support of the project
    #[serde(rename = "server_side", skip_serializing_if = "Option::is_none")]
    pub server_side: Option<ServerSide>,
}

impl BaseProject {
    pub fn new() -> BaseProject {
        BaseProject {
            slug: None,
            title: None,
            description: None,
            categories: None,
            client_side: None,
            server_side: None,
        }
    }
}
/// The client side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ClientSide {
    fn default() -> ClientSide {
        Self::Required
    }
}
/// The server side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServerSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ServerSide {
    fn default() -> ServerSide {
        Self::Required
    }
}
