/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryTag {
    /// The SVG icon of a category
    #[serde(rename = "icon")]
    pub icon: String,
    /// The name of the category
    #[serde(rename = "name")]
    pub name: String,
    /// The project type this category is applicable to
    #[serde(rename = "project_type")]
    pub project_type: String,
    /// The header under which the category should go
    #[serde(rename = "header")]
    pub header: String,
}

impl CategoryTag {
    pub fn new(icon: String, name: String, project_type: String, header: String) -> CategoryTag {
        CategoryTag {
            icon,
            name,
            project_type,
            header,
        }
    }
}
