/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatableReport {
    /// The type of the report being sent
    #[serde(rename = "report_type")]
    pub report_type: String,
    /// The ID of the item (project, version, or user) being reported
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The type of the item being reported
    #[serde(rename = "item_type")]
    pub item_type: ItemType,
    /// The extended explanation of the report
    #[serde(rename = "body")]
    pub body: String,
}

impl CreatableReport {
    pub fn new(
        report_type: String,
        item_id: String,
        item_type: ItemType,
        body: String,
    ) -> CreatableReport {
        CreatableReport {
            report_type,
            item_id,
            item_type,
            body,
        }
    }
}
/// The type of the item being reported
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ItemType {
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "version")]
    Version,
}

impl Default for ItemType {
    fn default() -> ItemType {
        Self::Project
    }
}
