/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatableProjectGalleryItem {
    /// The name of the multipart item where the gallery media is located
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    /// Whether the image is featured in the gallery
    #[serde(rename = "featured", skip_serializing_if = "Option::is_none")]
    pub featured: Option<bool>,
    /// The title of the gallery image
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    /// The description of the gallery image
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The order of the gallery image. Gallery images are sorted by this field and then alphabetically by title.
    #[serde(rename = "ordering", skip_serializing_if = "Option::is_none")]
    pub ordering: Option<i32>,
}

impl CreatableProjectGalleryItem {
    pub fn new() -> CreatableProjectGalleryItem {
        CreatableProjectGalleryItem {
            item: None,
            featured: None,
            title: None,
            description: None,
            ordering: None,
        }
    }
}
