/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatableVersion {
    /// The name of this version
    #[serde(rename = "name")]
    pub name: String,
    /// The version number. Ideally will follow semantic versioning
    #[serde(rename = "version_number")]
    pub version_number: String,
    /// The changelog for this version
    #[serde(
        rename = "changelog",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub changelog: Option<Option<String>>,
    /// A list of specific versions of projects that this version depends on
    #[serde(rename = "dependencies")]
    pub dependencies: Vec<models::VersionDependency>,
    /// A list of versions of Minecraft that this version supports
    #[serde(rename = "game_versions")]
    pub game_versions: Vec<String>,
    /// The release channel for this version
    #[serde(rename = "version_type")]
    pub version_type: VersionType,
    /// The mod loaders that this version supports. In case of resource packs, use \"minecraft\"
    #[serde(rename = "loaders")]
    pub loaders: Vec<String>,
    /// Whether the version is featured or not
    #[serde(rename = "featured")]
    pub featured: bool,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(
        rename = "requested_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requested_status: Option<Option<RequestedStatus>>,
    /// The ID of the project this version is for
    #[serde(rename = "project_id")]
    pub project_id: String,
    /// An array of the multipart field names of each file that goes with this version
    #[serde(rename = "file_parts")]
    pub file_parts: Vec<String>,
    /// The multipart field name of the primary file
    #[serde(rename = "primary_file", skip_serializing_if = "Option::is_none")]
    pub primary_file: Option<String>,
}

impl CreatableVersion {
    pub fn new(
        name: String,
        version_number: String,
        dependencies: Vec<models::VersionDependency>,
        game_versions: Vec<String>,
        version_type: VersionType,
        loaders: Vec<String>,
        featured: bool,
        project_id: String,
        file_parts: Vec<String>,
    ) -> CreatableVersion {
        CreatableVersion {
            name,
            version_number,
            changelog: None,
            dependencies,
            game_versions,
            version_type,
            loaders,
            featured,
            status: None,
            requested_status: None,
            project_id,
            file_parts,
            primary_file: None,
        }
    }
}
/// The release channel for this version
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VersionType {
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "beta")]
    Beta,
    #[serde(rename = "alpha")]
    Alpha,
}

impl Default for VersionType {
    fn default() -> VersionType {
        Self::Release
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "listed")]
    Listed,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Listed
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestedStatus {
    #[serde(rename = "listed")]
    Listed,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
}

impl Default for RequestedStatus {
    fn default() -> RequestedStatus {
        Self::Listed
    }
}
