/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatableProject {
    /// The slug of a project, used for vanity URLs. Regex: ```^[\\w!@$()`.+,\"\\-']{3,64}$```
    #[serde(rename = "slug")]
    pub slug: String,
    /// The title or name of the project
    #[serde(rename = "title")]
    pub title: String,
    /// A short description of the project
    #[serde(rename = "description")]
    pub description: String,
    /// A list of the categories that the project has
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
    /// The client side support of the project
    #[serde(rename = "client_side")]
    pub client_side: ClientSide,
    /// The server side support of the project
    #[serde(rename = "server_side")]
    pub server_side: ServerSide,
    /// A long form description of the project
    #[serde(rename = "body")]
    pub body: String,
    /// The status of the project
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// The requested status when submitting for review or scheduling the project for release
    #[serde(
        rename = "requested_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requested_status: Option<Option<RequestedStatus>>,
    /// A list of categories which are searchable but non-primary
    #[serde(
        rename = "additional_categories",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_categories: Option<Vec<String>>,
    /// An optional link to where to submit bugs or issues with the project
    #[serde(
        rename = "issues_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub issues_url: Option<Option<String>>,
    /// An optional link to the source code of the project
    #[serde(
        rename = "source_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_url: Option<Option<String>>,
    /// An optional link to the project's wiki page or other relevant information
    #[serde(
        rename = "wiki_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub wiki_url: Option<Option<String>>,
    /// An optional invite link to the project's discord
    #[serde(
        rename = "discord_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discord_url: Option<Option<String>>,
    /// A list of donation links for the project
    #[serde(rename = "donation_urls", skip_serializing_if = "Option::is_none")]
    pub donation_urls: Option<Vec<models::ProjectDonationUrl>>,
    /// The SPDX license ID of a project
    #[serde(rename = "license_id")]
    pub license_id: String,
    /// The URL to this license
    #[serde(
        rename = "license_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub license_url: Option<Option<String>>,
    #[serde(rename = "project_type")]
    pub project_type: ProjectType,
    /// A list of initial versions to upload with the created project. Deprecated - please upload version files after initial upload.
    #[serde(rename = "initial_versions", skip_serializing_if = "Option::is_none")]
    pub initial_versions: Option<Vec<models::EditableVersion>>,
    /// Whether the project should be saved as a draft instead of being sent to moderation for review. Deprecated - please always mark this as true.
    #[serde(rename = "is_draft", skip_serializing_if = "Option::is_none")]
    pub is_draft: Option<bool>,
    /// Gallery images to be uploaded with the created project. Deprecated - please upload gallery images after initial upload.
    #[serde(rename = "gallery_items", skip_serializing_if = "Option::is_none")]
    pub gallery_items: Option<Vec<models::CreatableProjectGalleryItem>>,
}

impl CreatableProject {
    pub fn new(
        slug: String,
        title: String,
        description: String,
        categories: Vec<String>,
        client_side: ClientSide,
        server_side: ServerSide,
        body: String,
        license_id: String,
        project_type: ProjectType,
    ) -> CreatableProject {
        CreatableProject {
            slug,
            title,
            description,
            categories,
            client_side,
            server_side,
            body,
            status: None,
            requested_status: None,
            additional_categories: None,
            issues_url: None,
            source_url: None,
            wiki_url: None,
            discord_url: None,
            donation_urls: None,
            license_id,
            license_url: None,
            project_type,
            initial_versions: None,
            is_draft: None,
            gallery_items: None,
        }
    }
}
/// The client side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ClientSide {
    fn default() -> ClientSide {
        Self::Required
    }
}
/// The server side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServerSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ServerSide {
    fn default() -> ServerSide {
        Self::Required
    }
}
/// The status of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "withheld")]
    Withheld,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Approved
    }
}
/// The requested status when submitting for review or scheduling the project for release
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestedStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "draft")]
    Draft,
}

impl Default for RequestedStatus {
    fn default() -> RequestedStatus {
        Self::Approved
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProjectType {
    #[serde(rename = "mod")]
    Mod,
    #[serde(rename = "modpack")]
    Modpack,
}

impl Default for ProjectType {
    fn default() -> ProjectType {
        Self::Mod
    }
}
