/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DonationPlatformTag {
    /// The short identifier of the donation platform
    #[serde(rename = "short")]
    pub short: String,
    /// The full name of the donation platform
    #[serde(rename = "name")]
    pub name: String,
}

impl DonationPlatformTag {
    pub fn new(short: String, name: String) -> DonationPlatformTag {
        DonationPlatformTag { short, name }
    }
}
