/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditableVersion {
    /// The name of this version
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The version number. Ideally will follow semantic versioning
    #[serde(rename = "version_number", skip_serializing_if = "Option::is_none")]
    pub version_number: Option<String>,
    /// The changelog for this version
    #[serde(
        rename = "changelog",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub changelog: Option<Option<String>>,
    /// A list of specific versions of projects that this version depends on
    #[serde(rename = "dependencies", skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<Vec<models::VersionDependency>>,
    /// A list of versions of Minecraft that this version supports
    #[serde(rename = "game_versions", skip_serializing_if = "Option::is_none")]
    pub game_versions: Option<Vec<String>>,
    /// The release channel for this version
    #[serde(rename = "version_type", skip_serializing_if = "Option::is_none")]
    pub version_type: Option<VersionType>,
    /// The mod loaders that this version supports. In case of resource packs, use \"minecraft\"
    #[serde(rename = "loaders", skip_serializing_if = "Option::is_none")]
    pub loaders: Option<Vec<String>>,
    /// Whether the version is featured or not
    #[serde(rename = "featured", skip_serializing_if = "Option::is_none")]
    pub featured: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(
        rename = "requested_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requested_status: Option<Option<RequestedStatus>>,
    /// The hash format and the hash of the new primary file
    #[serde(rename = "primary_file", skip_serializing_if = "Option::is_none")]
    pub primary_file: Option<Vec<String>>,
    /// A list of file_types to edit
    #[serde(rename = "file_types", skip_serializing_if = "Option::is_none")]
    pub file_types: Option<Vec<models::EditableFileType>>,
}

impl EditableVersion {
    pub fn new() -> EditableVersion {
        EditableVersion {
            name: None,
            version_number: None,
            changelog: None,
            dependencies: None,
            game_versions: None,
            version_type: None,
            loaders: None,
            featured: None,
            status: None,
            requested_status: None,
            primary_file: None,
            file_types: None,
        }
    }
}
/// The release channel for this version
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VersionType {
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "beta")]
    Beta,
    #[serde(rename = "alpha")]
    Alpha,
}

impl Default for VersionType {
    fn default() -> VersionType {
        Self::Release
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "listed")]
    Listed,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Listed
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestedStatus {
    #[serde(rename = "listed")]
    Listed,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
}

impl Default for RequestedStatus {
    fn default() -> RequestedStatus {
        Self::Listed
    }
}
