/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditableFileType {
    /// The hash algorithm of the hash specified in the hash field
    #[serde(rename = "algorithm")]
    pub algorithm: String,
    /// The hash of the file you're editing
    #[serde(rename = "hash")]
    pub hash: String,
    /// The hash algorithm of the file you're editing
    #[serde(rename = "file_type", deserialize_with = "Option::deserialize")]
    pub file_type: Option<models::FileTypeEnum>,
}

impl EditableFileType {
    pub fn new(
        algorithm: String,
        hash: String,
        file_type: Option<models::FileTypeEnum>,
    ) -> EditableFileType {
        EditableFileType {
            algorithm,
            hash,
            file_type,
        }
    }
}
