/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditableUser {
    /// The user's username
    #[serde(rename = "username")]
    pub username: String,
    /// The user's display name
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// The user's email (only displayed if requesting your own account). Requires `USER_READ_EMAIL` PAT scope.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// A description of the user
    #[serde(rename = "bio", skip_serializing_if = "Option::is_none")]
    pub bio: Option<String>,
    #[serde(
        rename = "payout_data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub payout_data: Option<Option<Box<models::UserPayoutData>>>,
}

impl EditableUser {
    pub fn new(username: String) -> EditableUser {
        EditableUser {
            username,
            name: None,
            email: None,
            bio: None,
            payout_data: None,
        }
    }
}
