/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileTypeEnum {
    #[serde(rename = "required-resource-pack")]
    RequiredResourcePack,
    #[serde(rename = "optional-resource-pack")]
    OptionalResourcePack,
    #[serde(rename = "sources-jar")]
    SourcesJar,
    #[serde(rename = "dev-jar")]
    DevJar,
    #[serde(rename = "javadoc-jar")]
    JavadocJar,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "signature")]
    Signature,
}

impl std::fmt::Display for FileTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RequiredResourcePack => write!(f, "required-resource-pack"),
            Self::OptionalResourcePack => write!(f, "optional-resource-pack"),
            Self::SourcesJar => write!(f, "sources-jar"),
            Self::DevJar => write!(f, "dev-jar"),
            Self::JavadocJar => write!(f, "javadoc-jar"),
            Self::Unknown => write!(f, "unknown"),
            Self::Signature => write!(f, "signature"),
        }
    }
}

impl Default for FileTypeEnum {
    fn default() -> FileTypeEnum {
        Self::RequiredResourcePack
    }
}
