/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// ForgeUpdateCheckerPromos : A list of the recommended and latest versions for each Minecraft release
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForgeUpdateCheckerPromos {
    /// The mod version that is recommended for `{version}`. Excludes versions with the `alpha` and `beta` version types.
    #[serde(
        rename = "{version}-recommended",
        skip_serializing_if = "Option::is_none"
    )]
    pub left_curly_bracket_version_right_curly_bracket__recommended: Option<String>,
    /// The latest mod version for `{version}`. Shows versions with the `alpha` and `beta` version types.
    #[serde(rename = "{version}-latest", skip_serializing_if = "Option::is_none")]
    pub left_curly_bracket_version_right_curly_bracket__latest: Option<String>,
}

impl ForgeUpdateCheckerPromos {
    /// A list of the recommended and latest versions for each Minecraft release
    pub fn new() -> ForgeUpdateCheckerPromos {
        ForgeUpdateCheckerPromos {
            left_curly_bracket_version_right_curly_bracket__recommended: None,
            left_curly_bracket_version_right_curly_bracket__latest: None,
        }
    }
}
