/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// ForgeUpdates : Mod version information that can be consumed by Forge's update checker
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForgeUpdates {
    /// A link to the mod page
    #[serde(rename = "homepage", skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    #[serde(rename = "promos", skip_serializing_if = "Option::is_none")]
    pub promos: Option<Box<models::ForgeUpdateCheckerPromos>>,
}

impl ForgeUpdates {
    /// Mod version information that can be consumed by Forge's update checker
    pub fn new() -> ForgeUpdates {
        ForgeUpdates {
            homepage: None,
            promos: None,
        }
    }
}
