/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GalleryImage {
    /// The URL of the gallery image
    #[serde(rename = "url")]
    pub url: String,
    /// Whether the image is featured in the gallery
    #[serde(rename = "featured")]
    pub featured: bool,
    /// The title of the gallery image
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    /// The description of the gallery image
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The date and time the gallery image was created
    #[serde(rename = "created")]
    pub created: String,
    /// The order of the gallery image. Gallery images are sorted by this field and then alphabetically by title.
    #[serde(rename = "ordering", skip_serializing_if = "Option::is_none")]
    pub ordering: Option<i32>,
}

impl GalleryImage {
    pub fn new(url: String, featured: bool, created: String) -> GalleryImage {
        GalleryImage {
            url,
            featured,
            title: None,
            description: None,
            created,
            ordering: None,
        }
    }
}
