/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameVersionTag {
    /// The name/number of the game version
    #[serde(rename = "version")]
    pub version: String,
    /// The type of the game version
    #[serde(rename = "version_type")]
    pub version_type: VersionType,
    /// The date of the game version release
    #[serde(rename = "date")]
    pub date: String,
    /// Whether or not this is a major version, used for Featured Versions
    #[serde(rename = "major")]
    pub major: bool,
}

impl GameVersionTag {
    pub fn new(
        version: String,
        version_type: VersionType,
        date: String,
        major: bool,
    ) -> GameVersionTag {
        GameVersionTag {
            version,
            version_type,
            date,
            major,
        }
    }
}
/// The type of the game version
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VersionType {
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "snapshot")]
    Snapshot,
    #[serde(rename = "alpha")]
    Alpha,
    #[serde(rename = "beta")]
    Beta,
}

impl Default for VersionType {
    fn default() -> VersionType {
        Self::Release
    }
}
