/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLatestVersionFromHashBody {
    #[serde(rename = "loaders")]
    pub loaders: Vec<String>,
    #[serde(rename = "game_versions")]
    pub game_versions: Vec<String>,
}

impl GetLatestVersionFromHashBody {
    pub fn new(loaders: Vec<String>, game_versions: Vec<String>) -> GetLatestVersionFromHashBody {
        GetLatestVersionFromHashBody {
            loaders,
            game_versions,
        }
    }
}
