/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLatestVersionsFromHashesBody {
    #[serde(rename = "hashes")]
    pub hashes: Vec<String>,
    #[serde(rename = "algorithm")]
    pub algorithm: Algorithm,
    #[serde(rename = "loaders")]
    pub loaders: Vec<String>,
    #[serde(rename = "game_versions")]
    pub game_versions: Vec<String>,
}

impl GetLatestVersionsFromHashesBody {
    pub fn new(
        hashes: Vec<String>,
        algorithm: Algorithm,
        loaders: Vec<String>,
        game_versions: Vec<String>,
    ) -> GetLatestVersionsFromHashesBody {
        GetLatestVersionsFromHashesBody {
            hashes,
            algorithm,
            loaders,
            game_versions,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Algorithm {
    #[serde(rename = "sha1")]
    Sha1,
    #[serde(rename = "sha512")]
    Sha512,
}

impl Default for Algorithm {
    fn default() -> Algorithm {
        Self::Sha1
    }
}
