/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// HashList : A list of hashes and the algorithm used to create them
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashList {
    #[serde(rename = "hashes")]
    pub hashes: Vec<String>,
    #[serde(rename = "algorithm")]
    pub algorithm: Algorithm,
}

impl HashList {
    /// A list of hashes and the algorithm used to create them
    pub fn new(hashes: Vec<String>, algorithm: Algorithm) -> HashList {
        HashList { hashes, algorithm }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Algorithm {
    #[serde(rename = "sha1")]
    Sha1,
    #[serde(rename = "sha512")]
    Sha512,
}

impl Default for Algorithm {
    fn default() -> Algorithm {
        Self::Sha1
    }
}
