/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// LicenseTag : A short overview of a license
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseTag {
    /// The short identifier of the license
    #[serde(rename = "short")]
    pub short: String,
    /// The full name of the license
    #[serde(rename = "name")]
    pub name: String,
}

impl LicenseTag {
    /// A short overview of a license
    pub fn new(short: String, name: String) -> LicenseTag {
        LicenseTag { short, name }
    }
}
