/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoaderTag {
    /// The SVG icon of a loader
    #[serde(rename = "icon")]
    pub icon: String,
    /// The name of the loader
    #[serde(rename = "name")]
    pub name: String,
    /// The project types that this loader is applicable to
    #[serde(rename = "supported_project_types")]
    pub supported_project_types: Vec<String>,
}

impl LoaderTag {
    pub fn new(icon: String, name: String, supported_project_types: Vec<String>) -> LoaderTag {
        LoaderTag {
            icon,
            name,
            supported_project_types,
        }
    }
}
