/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// ModeratorMessage : A message that a moderator sent regarding the project
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModeratorMessage {
    /// The message that a moderator has left for the project
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The longer body of the message that a moderator has left for the project
    #[serde(
        rename = "body",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub body: Option<Option<String>>,
}

impl ModeratorMessage {
    /// A message that a moderator sent regarding the project
    pub fn new() -> ModeratorMessage {
        ModeratorMessage {
            message: None,
            body: None,
        }
    }
}
