/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifyTeamMemberBody {
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// The user's permissions in bitfield format  In order from first to tenth bit, the bits are: - UPLOAD_VERSION - DELETE_VERSION - EDIT_DETAILS - EDIT_BODY - MANAGE_INVITES - REMOVE_MEMBER - EDIT_MEMBER - DELETE_PROJECT - VIEW_ANALYTICS - VIEW_PAYOUTS
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<i32>,
    /// The split of payouts going to this user. The proportion of payouts they get is their split divided by the sum of the splits of all members.
    #[serde(rename = "payouts_split", skip_serializing_if = "Option::is_none")]
    pub payouts_split: Option<i32>,
    /// The order of the team member.
    #[serde(rename = "ordering", skip_serializing_if = "Option::is_none")]
    pub ordering: Option<i32>,
}

impl ModifyTeamMemberBody {
    pub fn new() -> ModifyTeamMemberBody {
        ModifyTeamMemberBody {
            role: None,
            permissions: None,
            payouts_split: None,
            ordering: None,
        }
    }
}
