/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NonSearchProject {
    /// The slug of a project, used for vanity URLs. Regex: ```^[\\w!@$()`.+,\"\\-']{3,64}$```
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The title or name of the project
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// A short description of the project
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A list of the categories that the project has
    #[serde(rename = "categories", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Vec<String>>,
    /// The client side support of the project
    #[serde(rename = "client_side", skip_serializing_if = "Option::is_none")]
    pub client_side: Option<ClientSide>,
    /// The server side support of the project
    #[serde(rename = "server_side", skip_serializing_if = "Option::is_none")]
    pub server_side: Option<ServerSide>,
    /// A long form description of the project
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// The status of the project
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// The requested status when submitting for review or scheduling the project for release
    #[serde(
        rename = "requested_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requested_status: Option<Option<RequestedStatus>>,
    /// A list of categories which are searchable but non-primary
    #[serde(
        rename = "additional_categories",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_categories: Option<Vec<String>>,
    /// An optional link to where to submit bugs or issues with the project
    #[serde(
        rename = "issues_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub issues_url: Option<Option<String>>,
    /// An optional link to the source code of the project
    #[serde(
        rename = "source_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_url: Option<Option<String>>,
    /// An optional link to the project's wiki page or other relevant information
    #[serde(
        rename = "wiki_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub wiki_url: Option<Option<String>>,
    /// An optional invite link to the project's discord
    #[serde(
        rename = "discord_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discord_url: Option<Option<String>>,
    /// A list of donation links for the project
    #[serde(rename = "donation_urls", skip_serializing_if = "Option::is_none")]
    pub donation_urls: Option<Vec<models::ProjectDonationUrl>>,
}

impl NonSearchProject {
    pub fn new() -> NonSearchProject {
        NonSearchProject {
            slug: None,
            title: None,
            description: None,
            categories: None,
            client_side: None,
            server_side: None,
            body: None,
            status: None,
            requested_status: None,
            additional_categories: None,
            issues_url: None,
            source_url: None,
            wiki_url: None,
            discord_url: None,
            donation_urls: None,
        }
    }
}
/// The client side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ClientSide {
    fn default() -> ClientSide {
        Self::Required
    }
}
/// The server side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServerSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ServerSide {
    fn default() -> ServerSide {
        Self::Required
    }
}
/// The status of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "withheld")]
    Withheld,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Approved
    }
}
/// The requested status when submitting for review or scheduling the project for release
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestedStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "draft")]
    Draft,
}

impl Default for RequestedStatus {
    fn default() -> RequestedStatus {
        Self::Approved
    }
}
