/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Notification {
    /// The id of the notification
    #[serde(rename = "id")]
    pub id: String,
    /// The id of the user who received the notification
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// The type of notification
    #[serde(
        rename = "type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub r#type: Option<Option<Type>>,
    /// The title of the notification
    #[serde(rename = "title")]
    pub title: String,
    /// The body text of the notification
    #[serde(rename = "text")]
    pub text: String,
    /// A link to the related project or version
    #[serde(rename = "link")]
    pub link: String,
    /// Whether the notification has been read or not
    #[serde(rename = "read")]
    pub read: bool,
    /// The time at which the notification was created
    #[serde(rename = "created")]
    pub created: String,
    /// A list of actions that can be performed
    #[serde(rename = "actions")]
    pub actions: Vec<models::NotificationAction>,
}

impl Notification {
    pub fn new(
        id: String,
        user_id: String,
        title: String,
        text: String,
        link: String,
        read: bool,
        created: String,
        actions: Vec<models::NotificationAction>,
    ) -> Notification {
        Notification {
            id,
            user_id,
            r#type: None,
            title,
            text,
            link,
            read,
            created,
            actions,
        }
    }
}
/// The type of notification
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "project_update")]
    ProjectUpdate,
    #[serde(rename = "team_invite")]
    TeamInvite,
    #[serde(rename = "status_change")]
    StatusChange,
    #[serde(rename = "moderator_message")]
    ModeratorMessage,
}

impl Default for Type {
    fn default() -> Type {
        Self::ProjectUpdate
    }
}
