/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// NotificationAction : An action that can be performed on a notification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationAction {
    /// The friendly name for this action
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The HTTP code and path to request in order to perform this action.
    #[serde(rename = "action_route", skip_serializing_if = "Option::is_none")]
    pub action_route: Option<Vec<String>>,
}

impl NotificationAction {
    /// An action that can be performed on a notification
    pub fn new() -> NotificationAction {
        NotificationAction {
            title: None,
            action_route: None,
        }
    }
}
