/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchProjectsBody {
    /// Set all of the categories to the categories specified here
    #[serde(rename = "categories", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Vec<String>>,
    /// Add all of the categories specified here
    #[serde(rename = "add_categories", skip_serializing_if = "Option::is_none")]
    pub add_categories: Option<Vec<String>>,
    /// Remove all of the categories specified here
    #[serde(rename = "remove_categories", skip_serializing_if = "Option::is_none")]
    pub remove_categories: Option<Vec<String>>,
    /// Set all of the additional categories to the categories specified here
    #[serde(
        rename = "additional_categories",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_categories: Option<Vec<String>>,
    /// Add all of the additional categories specified here
    #[serde(
        rename = "add_additional_categories",
        skip_serializing_if = "Option::is_none"
    )]
    pub add_additional_categories: Option<Vec<String>>,
    /// Remove all of the additional categories specified here
    #[serde(
        rename = "remove_additional_categories",
        skip_serializing_if = "Option::is_none"
    )]
    pub remove_additional_categories: Option<Vec<String>>,
    /// Set all of the donation links to the donation links specified here
    #[serde(rename = "donation_urls", skip_serializing_if = "Option::is_none")]
    pub donation_urls: Option<Vec<models::ProjectDonationUrl>>,
    /// Add all of the donation links specified here
    #[serde(rename = "add_donation_urls", skip_serializing_if = "Option::is_none")]
    pub add_donation_urls: Option<Vec<models::ProjectDonationUrl>>,
    /// Remove all of the donation links specified here
    #[serde(
        rename = "remove_donation_urls",
        skip_serializing_if = "Option::is_none"
    )]
    pub remove_donation_urls: Option<Vec<models::ProjectDonationUrl>>,
    /// An optional link to where to submit bugs or issues with the projects
    #[serde(
        rename = "issues_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub issues_url: Option<Option<String>>,
    /// An optional link to the source code of the projects
    #[serde(
        rename = "source_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_url: Option<Option<String>>,
    /// An optional link to the projects' wiki page or other relevant information
    #[serde(
        rename = "wiki_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub wiki_url: Option<Option<String>>,
    /// An optional invite link to the projects' discord
    #[serde(
        rename = "discord_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discord_url: Option<Option<String>>,
}

impl PatchProjectsBody {
    pub fn new() -> PatchProjectsBody {
        PatchProjectsBody {
            categories: None,
            add_categories: None,
            remove_categories: None,
            additional_categories: None,
            add_additional_categories: None,
            remove_additional_categories: None,
            donation_urls: None,
            add_donation_urls: None,
            remove_donation_urls: None,
            issues_url: None,
            source_url: None,
            wiki_url: None,
            discord_url: None,
        }
    }
}
