/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Project {
    /// The slug of a project, used for vanity URLs. Regex: ```^[\\w!@$()`.+,\"\\-']{3,64}$```
    #[serde(rename = "slug")]
    pub slug: String,
    /// The title or name of the project
    #[serde(rename = "title")]
    pub title: String,
    /// A short description of the project
    #[serde(rename = "description")]
    pub description: String,
    /// A list of the categories that the project has
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
    /// The client side support of the project
    #[serde(rename = "client_side")]
    pub client_side: ClientSide,
    /// The server side support of the project
    #[serde(rename = "server_side")]
    pub server_side: ServerSide,
    /// A long form description of the project
    #[serde(rename = "body")]
    pub body: String,
    /// The status of the project
    #[serde(rename = "status")]
    pub status: Status,
    /// The requested status when submitting for review or scheduling the project for release
    #[serde(
        rename = "requested_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requested_status: Option<Option<RequestedStatus>>,
    /// A list of categories which are searchable but non-primary
    #[serde(
        rename = "additional_categories",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_categories: Option<Vec<String>>,
    /// An optional link to where to submit bugs or issues with the project
    #[serde(
        rename = "issues_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub issues_url: Option<Option<String>>,
    /// An optional link to the source code of the project
    #[serde(
        rename = "source_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_url: Option<Option<String>>,
    /// An optional link to the project's wiki page or other relevant information
    #[serde(
        rename = "wiki_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub wiki_url: Option<Option<String>>,
    /// An optional invite link to the project's discord
    #[serde(
        rename = "discord_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discord_url: Option<Option<String>>,
    /// A list of donation links for the project
    #[serde(rename = "donation_urls", skip_serializing_if = "Option::is_none")]
    pub donation_urls: Option<Vec<models::ProjectDonationUrl>>,
    /// The project type of the project
    #[serde(rename = "project_type")]
    pub project_type: ProjectType,
    /// The total number of downloads of the project
    #[serde(rename = "downloads")]
    pub downloads: i32,
    /// The URL of the project's icon
    #[serde(
        rename = "icon_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub icon_url: Option<Option<String>>,
    /// The RGB color of the project, automatically generated from the project icon
    #[serde(
        rename = "color",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub color: Option<Option<i32>>,
    /// The ID of the moderation thread associated with this project
    #[serde(rename = "thread_id", skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
    #[serde(
        rename = "monetization_status",
        skip_serializing_if = "Option::is_none"
    )]
    pub monetization_status: Option<MonetizationStatus>,
    /// The ID of the project, encoded as a base62 string
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the team that has ownership of this project
    #[serde(rename = "team")]
    pub team: String,
    /// The link to the long description of the project. Always null, only kept for legacy compatibility.
    #[serde(
        rename = "body_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub body_url: Option<Option<String>>,
    #[serde(
        rename = "moderator_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub moderator_message: Option<Option<Box<models::ModeratorMessage>>>,
    /// The date the project was published
    #[serde(rename = "published")]
    pub published: String,
    /// The date the project was last updated
    #[serde(rename = "updated")]
    pub updated: String,
    /// The date the project's status was set to an approved status
    #[serde(
        rename = "approved",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub approved: Option<Option<String>>,
    /// The date the project's status was submitted to moderators for review
    #[serde(
        rename = "queued",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub queued: Option<Option<String>>,
    /// The total number of users following the project
    #[serde(rename = "followers")]
    pub followers: i32,
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<Box<models::ProjectLicense>>,
    /// A list of the version IDs of the project (will never be empty unless `draft` status)
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<String>>,
    /// A list of all of the game versions supported by the project
    #[serde(rename = "game_versions", skip_serializing_if = "Option::is_none")]
    pub game_versions: Option<Vec<String>>,
    /// A list of all of the loaders supported by the project
    #[serde(rename = "loaders", skip_serializing_if = "Option::is_none")]
    pub loaders: Option<Vec<String>>,
    /// A list of images that have been uploaded to the project's gallery
    #[serde(rename = "gallery", skip_serializing_if = "Option::is_none")]
    pub gallery: Option<Vec<models::GalleryImage>>,
}

impl Project {
    pub fn new(
        slug: String,
        title: String,
        description: String,
        categories: Vec<String>,
        client_side: ClientSide,
        server_side: ServerSide,
        body: String,
        status: Status,
        project_type: ProjectType,
        downloads: i32,
        id: String,
        team: String,
        published: String,
        updated: String,
        followers: i32,
    ) -> Project {
        Project {
            slug,
            title,
            description,
            categories,
            client_side,
            server_side,
            body,
            status,
            requested_status: None,
            additional_categories: None,
            issues_url: None,
            source_url: None,
            wiki_url: None,
            discord_url: None,
            donation_urls: None,
            project_type,
            downloads,
            icon_url: None,
            color: None,
            thread_id: None,
            monetization_status: None,
            id,
            team,
            body_url: None,
            moderator_message: None,
            published,
            updated,
            approved: None,
            queued: None,
            followers,
            license: None,
            versions: None,
            game_versions: None,
            loaders: None,
            gallery: None,
        }
    }
}
/// The client side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ClientSide {
    fn default() -> ClientSide {
        Self::Required
    }
}
/// The server side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServerSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ServerSide {
    fn default() -> ServerSide {
        Self::Required
    }
}
/// The status of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "withheld")]
    Withheld,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Approved
    }
}
/// The requested status when submitting for review or scheduling the project for release
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestedStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "draft")]
    Draft,
}

impl Default for RequestedStatus {
    fn default() -> RequestedStatus {
        Self::Approved
    }
}
/// The project type of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProjectType {
    #[serde(rename = "mod")]
    Mod,
    #[serde(rename = "modpack")]
    Modpack,
    #[serde(rename = "resourcepack")]
    Resourcepack,
    #[serde(rename = "shader")]
    Shader,
}

impl Default for ProjectType {
    fn default() -> ProjectType {
        Self::Mod
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MonetizationStatus {
    #[serde(rename = "monetized")]
    Monetized,
    #[serde(rename = "demonetized")]
    Demonetized,
    #[serde(rename = "force-demonetized")]
    ForceDemonetized,
}

impl Default for MonetizationStatus {
    fn default() -> MonetizationStatus {
        Self::Monetized
    }
}
