/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectDependencyList {
    /// Projects that the project depends upon
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<models::Project>>,
    /// Versions that the project depends upon
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<models::Version>>,
}

impl ProjectDependencyList {
    pub fn new() -> ProjectDependencyList {
        ProjectDependencyList {
            projects: None,
            versions: None,
        }
    }
}
