/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Report {
    /// The type of the report being sent
    #[serde(rename = "report_type")]
    pub report_type: String,
    /// The ID of the item (project, version, or user) being reported
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The type of the item being reported
    #[serde(rename = "item_type")]
    pub item_type: ItemType,
    /// The extended explanation of the report
    #[serde(rename = "body")]
    pub body: String,
    /// The ID of the report
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The ID of the user who reported the item
    #[serde(rename = "reporter")]
    pub reporter: String,
    /// The time at which the report was created
    #[serde(rename = "created")]
    pub created: String,
    /// Whether the report is resolved
    #[serde(rename = "closed")]
    pub closed: bool,
    /// The ID of the moderation thread associated with this report
    #[serde(rename = "thread_id")]
    pub thread_id: String,
}

impl Report {
    pub fn new(
        report_type: String,
        item_id: String,
        item_type: ItemType,
        body: String,
        reporter: String,
        created: String,
        closed: bool,
        thread_id: String,
    ) -> Report {
        Report {
            report_type,
            item_id,
            item_type,
            body,
            id: None,
            reporter,
            created,
            closed,
            thread_id,
        }
    }
}
/// The type of the item being reported
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ItemType {
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "version")]
    Version,
}

impl Default for ItemType {
    fn default() -> ItemType {
        Self::Project
    }
}
