/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Schedule {
    #[serde(rename = "time")]
    pub time: String,
    /// The requested status when scheduling the project for release
    #[serde(rename = "requested_status")]
    pub requested_status: RequestedStatus,
}

impl Schedule {
    pub fn new(time: String, requested_status: RequestedStatus) -> Schedule {
        Schedule {
            time,
            requested_status,
        }
    }
}
/// The requested status when scheduling the project for release
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestedStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "draft")]
    Draft,
}

impl Default for RequestedStatus {
    fn default() -> RequestedStatus {
        Self::Approved
    }
}
