/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerRenderedProject {
    /// The slug of a project, used for vanity URLs. Regex: ```^[\\w!@$()`.+,\"\\-']{3,64}$```
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The title or name of the project
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// A short description of the project
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A list of the categories that the project has
    #[serde(rename = "categories", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Vec<String>>,
    /// The client side support of the project
    #[serde(rename = "client_side", skip_serializing_if = "Option::is_none")]
    pub client_side: Option<ClientSide>,
    /// The server side support of the project
    #[serde(rename = "server_side", skip_serializing_if = "Option::is_none")]
    pub server_side: Option<ServerSide>,
    /// The project type of the project
    #[serde(rename = "project_type")]
    pub project_type: ProjectType,
    /// The total number of downloads of the project
    #[serde(rename = "downloads")]
    pub downloads: i32,
    /// The URL of the project's icon
    #[serde(
        rename = "icon_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub icon_url: Option<Option<String>>,
    /// The RGB color of the project, automatically generated from the project icon
    #[serde(
        rename = "color",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub color: Option<Option<i32>>,
    /// The ID of the moderation thread associated with this project
    #[serde(rename = "thread_id", skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
    #[serde(
        rename = "monetization_status",
        skip_serializing_if = "Option::is_none"
    )]
    pub monetization_status: Option<MonetizationStatus>,
}

impl ServerRenderedProject {
    pub fn new(project_type: ProjectType, downloads: i32) -> ServerRenderedProject {
        ServerRenderedProject {
            slug: None,
            title: None,
            description: None,
            categories: None,
            client_side: None,
            server_side: None,
            project_type,
            downloads,
            icon_url: None,
            color: None,
            thread_id: None,
            monetization_status: None,
        }
    }
}
/// The client side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ClientSide {
    fn default() -> ClientSide {
        Self::Required
    }
}
/// The server side support of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServerSide {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for ServerSide {
    fn default() -> ServerSide {
        Self::Required
    }
}
/// The project type of the project
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProjectType {
    #[serde(rename = "mod")]
    Mod,
    #[serde(rename = "modpack")]
    Modpack,
    #[serde(rename = "resourcepack")]
    Resourcepack,
    #[serde(rename = "shader")]
    Shader,
}

impl Default for ProjectType {
    fn default() -> ProjectType {
        Self::Mod
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MonetizationStatus {
    #[serde(rename = "monetized")]
    Monetized,
    #[serde(rename = "demonetized")]
    Demonetized,
    #[serde(rename = "force-demonetized")]
    ForceDemonetized,
}

impl Default for MonetizationStatus {
    fn default() -> MonetizationStatus {
        Self::Monetized
    }
}
