/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Statistics {
    /// Number of projects on Modrinth
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<i32>,
    /// Number of versions on Modrinth
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<i32>,
    /// Number of version files on Modrinth
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<i32>,
    /// Number of authors (users with projects) on Modrinth
    #[serde(rename = "authors", skip_serializing_if = "Option::is_none")]
    pub authors: Option<i32>,
}

impl Statistics {
    pub fn new() -> Statistics {
        Statistics {
            projects: None,
            versions: None,
            files: None,
            authors: None,
        }
    }
}
