/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Thread {
    /// The ID of the thread
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The ID of the associated project if a project thread
    #[serde(
        rename = "project_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub project_id: Option<Option<String>>,
    /// The ID of the associated report if a report thread
    #[serde(
        rename = "report_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub report_id: Option<Option<String>>,
    #[serde(rename = "messages")]
    pub messages: Vec<models::ThreadMessage>,
    #[serde(rename = "members")]
    pub members: Vec<models::User>,
}

impl Thread {
    pub fn new(
        id: String,
        r#type: Type,
        messages: Vec<models::ThreadMessage>,
        members: Vec<models::User>,
    ) -> Thread {
        Thread {
            id,
            r#type,
            project_id: None,
            report_id: None,
            messages,
            members,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "report")]
    Report,
    #[serde(rename = "direct_message")]
    DirectMessage,
}

impl Default for Type {
    fn default() -> Type {
        Self::Project
    }
}
