/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// ThreadMessageBody : The contents of the message. **Fields will vary depending on message type.**
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadMessageBody {
    /// The type of message
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The actual message text. **Only present for `text` message type**
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// Whether the message is only visible to moderators. **Only present for `text` message type**
    #[serde(rename = "private", skip_serializing_if = "Option::is_none")]
    pub private: Option<bool>,
    /// The ID of the message being replied to by this message. **Only present for `text` message type**
    #[serde(
        rename = "replying_to",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub replying_to: Option<Option<String>>,
    /// The old status of the project. **Only present for `status_change` message type**
    #[serde(rename = "old_status", skip_serializing_if = "Option::is_none")]
    pub old_status: Option<OldStatus>,
    /// The new status of the project. **Only present for `status_change` message type**
    #[serde(rename = "new_status", skip_serializing_if = "Option::is_none")]
    pub new_status: Option<NewStatus>,
}

impl ThreadMessageBody {
    /// The contents of the message. **Fields will vary depending on message type.**
    pub fn new(r#type: Type) -> ThreadMessageBody {
        ThreadMessageBody {
            r#type,
            body: None,
            private: None,
            replying_to: None,
            old_status: None,
            new_status: None,
        }
    }
}
/// The type of message
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "status_change")]
    StatusChange,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "thread_closure")]
    ThreadClosure,
    #[serde(rename = "deleted")]
    Deleted,
}

impl Default for Type {
    fn default() -> Type {
        Self::StatusChange
    }
}
/// The old status of the project. **Only present for `status_change` message type**
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OldStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "withheld")]
    Withheld,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for OldStatus {
    fn default() -> OldStatus {
        Self::Approved
    }
}
/// The new status of the project. **Only present for `status_change` message type**
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NewStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "withheld")]
    Withheld,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for NewStatus {
    fn default() -> NewStatus {
        Self::Approved
    }
}
