/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadMessage {
    /// The ID of the message itself
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the author
    #[serde(
        rename = "author_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub author_id: Option<Option<String>>,
    #[serde(rename = "body")]
    pub body: Box<models::ThreadMessageBody>,
    /// The time at which the message was created
    #[serde(rename = "created")]
    pub created: String,
}

impl ThreadMessage {
    pub fn new(id: String, body: models::ThreadMessageBody, created: String) -> ThreadMessage {
        ThreadMessage {
            id,
            author_id: None,
            body: Box::new(body),
            created,
        }
    }
}
