/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPayoutHistoryEntry {
    /// The date of this transaction
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// The amount of this transaction in USD
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i32>,
    /// The status of this transaction
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl UserPayoutHistoryEntry {
    pub fn new() -> UserPayoutHistoryEntry {
        UserPayoutHistoryEntry {
            created: None,
            amount: None,
            status: None,
        }
    }
}
