/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// The user's username
    #[serde(rename = "username")]
    pub username: String,
    /// The user's display name
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// The user's email (only displayed if requesting your own account). Requires `USER_READ_EMAIL` PAT scope.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// A description of the user
    #[serde(rename = "bio", skip_serializing_if = "Option::is_none")]
    pub bio: Option<String>,
    #[serde(
        rename = "payout_data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub payout_data: Option<Option<Box<models::UserPayoutData>>>,
    /// The user's ID
    #[serde(rename = "id")]
    pub id: String,
    /// The user's avatar url
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
    /// The time at which the user was created
    #[serde(rename = "created")]
    pub created: String,
    /// The user's role
    #[serde(rename = "role")]
    pub role: Role,
    /// Any badges applicable to this user. These are currently unused and undisplayed, and as such are subject to change  In order from first to seventh bit, the current bits are: - (unused) - EARLY_MODPACK_ADOPTER - EARLY_RESPACK_ADOPTER - EARLY_PLUGIN_ADOPTER - ALPHA_TESTER - CONTRIBUTOR - TRANSLATOR
    #[serde(rename = "badges", skip_serializing_if = "Option::is_none")]
    pub badges: Option<i32>,
    /// A list of authentication providers you have signed up for (only displayed if requesting your own account)
    #[serde(
        rename = "auth_providers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub auth_providers: Option<Option<Vec<String>>>,
    /// Whether your email is verified (only displayed if requesting your own account)
    #[serde(
        rename = "email_verified",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email_verified: Option<Option<bool>>,
    /// Whether you have a password associated with your account (only displayed if requesting your own account)
    #[serde(
        rename = "has_password",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_password: Option<Option<bool>>,
    /// Whether you have TOTP two-factor authentication connected to your account (only displayed if requesting your own account)
    #[serde(
        rename = "has_totp",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_totp: Option<Option<bool>>,
    /// Deprecated - this is no longer public for security reasons and is always null
    #[serde(
        rename = "github_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub github_id: Option<Option<i32>>,
}

impl User {
    pub fn new(
        username: String,
        id: String,
        avatar_url: String,
        created: String,
        role: Role,
    ) -> User {
        User {
            username,
            name: None,
            email: None,
            bio: None,
            payout_data: None,
            id,
            avatar_url,
            created,
            role,
            badges: None,
            auth_providers: None,
            email_verified: None,
            has_password: None,
            has_totp: None,
            github_id: None,
        }
    }
}
/// The user's role
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "moderator")]
    Moderator,
    #[serde(rename = "developer")]
    Developer,
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}
