/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPayoutHistory {
    /// The all-time balance accrued by this user in USD
    #[serde(rename = "all_time", skip_serializing_if = "Option::is_none")]
    pub all_time: Option<String>,
    /// The amount in USD made by the user in the previous 30 days
    #[serde(rename = "last_month", skip_serializing_if = "Option::is_none")]
    pub last_month: Option<String>,
    /// A history of all of the user's past transactions
    #[serde(rename = "payouts", skip_serializing_if = "Option::is_none")]
    pub payouts: Option<Vec<models::UserPayoutHistoryEntry>>,
}

impl UserPayoutHistory {
    pub fn new() -> UserPayoutHistory {
        UserPayoutHistory {
            all_time: None,
            last_month: None,
            payouts: None,
        }
    }
}
