/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserIdentifier {
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl UserIdentifier {
    pub fn new(user_id: String) -> UserIdentifier {
        UserIdentifier { user_id }
    }
}
