/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// UserPayoutData : Various data relating to the user's payouts status (you can only see your own)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPayoutData {
    /// The payout balance available for the user to withdraw (note, you cannot modify this in a PATCH request)
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<i32>,
    /// The wallet that the user has selected
    #[serde(rename = "payout_wallet", skip_serializing_if = "Option::is_none")]
    pub payout_wallet: Option<PayoutWallet>,
    /// The type of the user's wallet
    #[serde(rename = "payout_wallet_type", skip_serializing_if = "Option::is_none")]
    pub payout_wallet_type: Option<PayoutWalletType>,
    /// The user's payout address
    #[serde(rename = "payout_address", skip_serializing_if = "Option::is_none")]
    pub payout_address: Option<String>,
}

impl UserPayoutData {
    /// Various data relating to the user's payouts status (you can only see your own)
    pub fn new() -> UserPayoutData {
        UserPayoutData {
            balance: None,
            payout_wallet: None,
            payout_wallet_type: None,
            payout_address: None,
        }
    }
}
/// The wallet that the user has selected
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayoutWallet {
    #[serde(rename = "paypal")]
    Paypal,
    #[serde(rename = "venmo")]
    Venmo,
}

impl Default for PayoutWallet {
    fn default() -> PayoutWallet {
        Self::Paypal
    }
}
/// The type of the user's wallet
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayoutWalletType {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "phone")]
    Phone,
    #[serde(rename = "user_handle")]
    UserHandle,
}

impl Default for PayoutWalletType {
    fn default() -> PayoutWalletType {
        Self::Email
    }
}
