/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionDependency {
    /// The ID of the version that this version depends on
    #[serde(
        rename = "version_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub version_id: Option<Option<String>>,
    /// The ID of the project that this version depends on
    #[serde(
        rename = "project_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub project_id: Option<Option<String>>,
    /// The file name of the dependency, mostly used for showing external dependencies on modpacks
    #[serde(
        rename = "file_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub file_name: Option<Option<String>>,
    /// The type of dependency that this version has
    #[serde(rename = "dependency_type")]
    pub dependency_type: DependencyType,
}

impl VersionDependency {
    pub fn new(dependency_type: DependencyType) -> VersionDependency {
        VersionDependency {
            version_id: None,
            project_id: None,
            file_name: None,
            dependency_type,
        }
    }
}
/// The type of dependency that this version has
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DependencyType {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "optional")]
    Optional,
    #[serde(rename = "incompatible")]
    Incompatible,
    #[serde(rename = "embedded")]
    Embedded,
}

impl Default for DependencyType {
    fn default() -> DependencyType {
        Self::Required
    }
}
