/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Version {
    /// The name of this version
    #[serde(rename = "name")]
    pub name: String,
    /// The version number. Ideally will follow semantic versioning
    #[serde(rename = "version_number")]
    pub version_number: String,
    /// The changelog for this version
    #[serde(
        rename = "changelog",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub changelog: Option<Option<String>>,
    /// A list of specific versions of projects that this version depends on
    #[serde(rename = "dependencies", skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<Vec<models::VersionDependency>>,
    /// A list of versions of Minecraft that this version supports
    #[serde(rename = "game_versions")]
    pub game_versions: Vec<String>,
    /// The release channel for this version
    #[serde(rename = "version_type")]
    pub version_type: VersionType,
    /// The mod loaders that this version supports. In case of resource packs, use \"minecraft\"
    #[serde(rename = "loaders")]
    pub loaders: Vec<String>,
    /// Whether the version is featured or not
    #[serde(rename = "featured")]
    pub featured: bool,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(
        rename = "requested_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requested_status: Option<Option<RequestedStatus>>,
    /// The ID of the version, encoded as a base62 string
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the project this version is for
    #[serde(rename = "project_id")]
    pub project_id: String,
    /// The ID of the author who published this version
    #[serde(rename = "author_id")]
    pub author_id: String,
    #[serde(rename = "date_published")]
    pub date_published: String,
    /// The number of times this version has been downloaded
    #[serde(rename = "downloads")]
    pub downloads: i32,
    /// A link to the changelog for this version. Always null, only kept for legacy compatibility.
    #[serde(
        rename = "changelog_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub changelog_url: Option<Option<String>>,
    /// A list of files available for download for this version
    #[serde(rename = "files")]
    pub files: Vec<models::VersionFile>,
}

impl Version {
    pub fn new(
        name: String,
        version_number: String,
        game_versions: Vec<String>,
        version_type: VersionType,
        loaders: Vec<String>,
        featured: bool,
        id: String,
        project_id: String,
        author_id: String,
        date_published: String,
        downloads: i32,
        files: Vec<models::VersionFile>,
    ) -> Version {
        Version {
            name,
            version_number,
            changelog: None,
            dependencies: None,
            game_versions,
            version_type,
            loaders,
            featured,
            status: None,
            requested_status: None,
            id,
            project_id,
            author_id,
            date_published,
            downloads,
            changelog_url: None,
            files,
        }
    }
}
/// The release channel for this version
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VersionType {
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "beta")]
    Beta,
    #[serde(rename = "alpha")]
    Alpha,
}

impl Default for VersionType {
    fn default() -> VersionType {
        Self::Release
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "listed")]
    Listed,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Listed
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestedStatus {
    #[serde(rename = "listed")]
    Listed,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "unlisted")]
    Unlisted,
}

impl Default for RequestedStatus {
    fn default() -> RequestedStatus {
        Self::Listed
    }
}
