/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

/// VersionFileHashes : A map of hashes of the file. The key is the hashing algorithm and the value is the string version of the hash.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionFileHashes {
    #[serde(rename = "sha512", skip_serializing_if = "Option::is_none")]
    pub sha512: Option<String>,
    #[serde(rename = "sha1", skip_serializing_if = "Option::is_none")]
    pub sha1: Option<String>,
}

impl VersionFileHashes {
    /// A map of hashes of the file. The key is the hashing algorithm and the value is the string version of the hash.
    pub fn new() -> VersionFileHashes {
        VersionFileHashes {
            sha512: None,
            sha1: None,
        }
    }
}
