/*
 * Labrinth
 *
 * The version of the OpenAPI document: v2.7.0/366f528
 * Generated by: https://openapi-generator.tech
 */

use super as models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionFile {
    #[serde(rename = "hashes")]
    pub hashes: Box<models::VersionFileHashes>,
    /// A direct link to the file
    #[serde(rename = "url")]
    pub url: String,
    /// The name of the file
    #[serde(rename = "filename")]
    pub filename: String,
    /// Whether this file is the primary one for its version. Only a maximum of one file per version will have this set to true. If there are not any primary files, it can be inferred that the first file is the primary one.
    #[serde(rename = "primary")]
    pub primary: bool,
    /// The size of the file in bytes
    #[serde(rename = "size")]
    pub size: i32,
    /// The type of the additional file, used mainly for adding resource packs to datapacks
    #[serde(
        rename = "file_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub file_type: Option<Option<models::FileTypeEnum>>,
}

impl VersionFile {
    pub fn new(
        hashes: models::VersionFileHashes,
        url: String,
        filename: String,
        primary: bool,
        size: i32,
    ) -> VersionFile {
        VersionFile {
            hashes: Box::new(hashes),
            url,
            filename,
            primary,
            size,
            file_type: None,
        }
    }
}
